def load_bucket() -> dict[str, list]:
	bucket = {
    "owner":[
        "Co Founder",
        "Chair and Chief Executive Officer",
        "Chairman Committee",
        "Co-owner",
        "Chancellor",
        "Partner",
        "Owner",
        "Coowner",
        "Chair-man",
        "Chairperson",
        "CP",
        "Chairwomen",
        "Co owner",
        "Chair Man",
        "Cofounder",
        "Founder",
        "Chairman",
        "Co-Founder",
        "C.P",
        "Chair-person",
        "Trustee"
    ],
    "cxo":[
        "C.H.O",
        "Chief Vision Officer",
        "CTO",
        "Chair and Chief Executive Officer",
        "CEO",
        "Chief Creative Officer",
        "Partner",
        "Chief Executives Officer",
        "Coowner",
        "CPO",
        "Chair-man",
        "C.E.O",
        "Chairperson",
        "Chief Financial Officer",
        "CDO",
        "Chief Digital and Analytics Officer",
        "Chief Business Officer",
        "C.I.O",
        "CVO",
        "Chief Distribution Officer",
        "Chief Information Security Officer",
        "CBO",
        "Trustee",
        "Co-Chief Executive Officer",
        "CIO",
        "CGO",
        "C.T.O",
        "Chief Operations Officer",
        "Co Founder",
        "C.M.O",
        "Chancellor",
        "Chief executive officer",
        "CRO",
        "C.G.O",
        "Chief Technology Officer",
        "C.I.S.O",
        "CSO",
        "Chairwomen",
        "Chair Man",
        "Chief Peoples Officer",
        "C.C.O",
        "Chief Analytics Officer",
        "COO",
        "Chief Compliance Officer",
        "Chairman",
        "C.D.A.O",
        "C.B.O",
        "Co-Founder",
        "CAO",
        "Chief Operating Officer",
        "C.P",
        "Chief Human Resource Officer",
        "Chair-person",
        "Chief Product Officer",
        "Chief Strategy Officer",
        "CDAO",
        "Chairman Committee",
        "CMO",
        "Chief Revenue Officer",
        "CUO",
        "C.F.O",
        "C.S.O",
        "Chief Development Officer",
        "Chief Hygiene Officer",
        "Chief Information Officer",
        "CFO",
        "Chief Technical officer",
        "CISO",
        "C.U.O",
        "Cofounder",
        "CCO",
        "Chief Growth Officer",
        "C.H.R.O",
        "Chief Results Officer",
        "C.R.O",
        "Chief Commercial Officer",
        "Chief Underwriting Officer",
        "Chief Data Officer",
        "CHRO",
        "Chief Technologist",
        "Co-owner",
        "CHO",
        "Chief Cultural Officer",
        "C.D.O",
        "Owner",
        "C.P.O",
        "CP",
        "Chief Marketing Officer",
        "Co owner",
        "Chief People Officer",
        "Chief Digital Officer",
        "Founder",
        "C.A.O",
        "C.O.O",
        "C.V.O"
    ],
    "director":[
        "Managing Director",
        "Director Of Product Management",
        "Sales Director",
        "Executive Director",
        "Director General",
        "Marketing Director",
        "Visionary Director",
        "Strategic Account Director",
        "Talent Acquisition Director",
        "Director of Sustainability",
        "Administrative Director",
        "Affiliate Director",
        "Senior Director",
        "Contract Director",
        "Portfolio Director",
        "Regional Director",
        "Associate Director",
        "Board Of Directors",
        "Business development Director",
        "IT Director",
        "Finance Director",
        "Technology Director",
        "Commercial Director",
        "Company IT Director",
        "Creative Director",
        "Deputy Director",
        "Development Director",
        "Director Of Applications",
        "Director of Behavioural Health",
        "Director CSR",
        "Director Marketing",
        "Group Director",
        "Global Director",
        "HR Director",
        "Interim Finance Director",
        "Director"
    ],
    "partner":[
        "Advisory Board Member",
        "Area Managing Partner",
        "Board Advisor",
        "Board Treasurer",
        "Board Trustee",
        "Managing Partner",
        "Senior Managing Partner",
        "Founding Partner",
        "Associate Partner",
        "Limited Partner",
        "Commercial Strategy Partner",
        "Investor ",
        "Shareholder",
        "Venture Partner",
        "General Partner",
        "Operational Partner",
        "Member Board of trustees"
    ],
    "senior":[
        "Senior Business Analyst",
        "Senior Finance Consultant",
        "Senior Client Advisor",
        "Senior Editor",
        "Senior Managing Editor",
        "Senior HR Recruitment",
        "Senior Marketing Specialist",
        "Senior Advisor",
        "Senior Exceutive",
        "Senior Technical Recruitor",
        "Senior Consultant",
        "Executive",
        "Lead Manager"
    ],
    "vp":[
        "Vice President",
        "Deputy Vp",
        "Executive VP",
        "Global VP",
        "VP HR",
        "Assistant Vice President",
        "Marketing VP",
        "S.V.P Operations",
        "Executive Vice President",
        "Deputy Vice President",
        "Senior Vice President"
    ],
    "manager":[
        "Talent Acquisition manager",
        "Lead",
        "Project Manager",
        "Country Manager",
        "Human Resource Manager",
        "Global Business Manager",
        "Assistant Manager",
        "Sr HR manager",
        "Event Sales Manager",
        "Deputy manager",
        "General Manager",
        "Regional manager",
        "Executive Manager",
        "Product Manager",
        "Technical Manager",
        "Jr. HR Manager",
        "Growth Marketing Manager",
        "Marketing Manager",
        "Senior Manager"
    ],
    "entry":[
        "Associate",
        "Affiliate",
        "Agent ",
        "Analyst",
        "Blogger",
        "Committee Member",
        "Content Writer",
        "Content Creator",
        "Collaborator",
        "Data Scientist",
        "Digital Operations",
        "Ecommerce",
        "Finance Associate",
        "Freelancer",
        "Learning Officer",
        "Leaning Specialist",
        "Hr Learning",
        "Humanitarian"
    ],
    "training":[
        "Interns",
        "Technical Training",
        "Public Policy Intern ",
        "Logistics Intern",
        "Software Engineer Intern",
        "Student",
        "Process safety Intern"
    ],
    "unpaid":[
        "Actively Looking",
        "Actively seeking employment",
        "Volunteer",
        "Career Break",
        "Former Chairman",
        "Former Owner",
        "Ex President",
        "Maternity Leave",
        "Newly Retired",
        "partially retired",
        "Parental Leave",
        "Pandemic UnEmployeed",
        "Study Leave ",
        "Time Off"
    ]
	}

	return bucket